service: ws

runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

vpc_access_connector:
  name: projects/gae-lab-001/locations/us-central1/connectors/nats-1-vm-connector

env_variables:
  QS_NATS_URL: nats:WKhppQ42XEEd@10.142.0.2:4222